### ISSUE TITLE
Can't pickup Pocket Dimension with Wrench

### ISSUE THREAD

**Issue by AxtTom** [TheCosmicNebula/DimensionalPocketsII#75]
Error in Console:
`[Server thread/FATAL] [minecraft/MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at com.zeher.dimpockets.pocket.core.tileentity.TilePocket.generateItemStackOnRemoval(TilePocket.java:311) ~[TilePocket.class:?]
        at com.zeher.dimpockets.pocket.core.tileentity.TilePocket.onBlockActivated(TilePocket.java:257) ~[TilePocket.class:?]
        at com.zeher.dimpockets.pocket.core.block.BlockPocket.func_180639_a(BlockPocket.java:79) ~[BlockPocket.class:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:449) ~[or.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:741) ~[pa.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[ma.class:?]
        at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[ma.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_281]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_281]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
        ... 5 more`

**Comment by TheCosmicNebula** [comment]
What version of the mod are you running?

**Comment by AxtTom** [comment]
._. I just looked at the filename to find out the version and im using `dimensionapocketsii-1.12.2-5.2.101-beta-clientonly`... cleintonly on a server, i guess theres the problem. sorry
